version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper
        ports: ["2181:2181"]
        hostname: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "10000"
            ZOOKEEPER_SYNC_LIMIT: "5"
        networks: [experiment]
    broker:
        image: confluentinc/cp-kafka
        ports: ["9092:9092"]
        hostname: broker
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:9092"
        depends_on:
            - zookeeper
        networks: [experiment]
    schema_registry:
        image: confluentinc/cp-schema-registry
        ports: ["9090:9090"]
        hostname: schema_registry
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
            SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:9090"
        depends_on:
            - zookeeper
        networks: [experiment]
    kafka_rest:
        image: confluentinc/cp-kafka-rest
        ports: ["9091:9091"]
        hostname: kafka_rest
        environment:
            KAFKA_REST_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_REST_LISTENERS: "http://kafka_rest:9091"
            KAFKA_REST_SCHEMA_REGISTRY_URL: "http://schema_registry:9090"
        depends_on:
            - zookeeper
            - schema_registry
        networks: [experiment]
    kafka_control_center:
        image: confluentinc/cp-enterprise-control-center
        ports: ["2180:2180"]
        hostname: kafka_control_center
        environment:
            CONTROL_CENTER_ZOOKEEPER_CONNECT: "zookeeper:2181"
            CONTROL_CENTER_BOOTSTRAP_SERVERS: "broker:9092"
            CONTROL_CENTER_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
            - broker
        ulimits:
            nofile:
                soft: 16384
                hard: 16384
        networks: [experiment]
        
