version: "3.3"

services:
    applications:
        image: eu.gcr.io/kite-221910/kafka-experiments-applications:latest
        ports: ["9093:9093", "9198:9198"]
        environment:
            APPLICATIONS_SERVICE_PORT: "9093"
            APPLICATIONS_SERVICE_MANAGEMENT_PORT: "9198"
            KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
            KAFKA_ZK_NODES: "zookeeper:2181"
            KAFKA_SCHEMA_REGISTRY: "http://schema_registry:9090"
            EUREKA_DEFAULT_ZONE_URL: "http://discovery:8761/eureka"
            ZIPKIN_URL: http://zipkin:9252
            POSTGRES_SERVER: "postgres:5432"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "hahaha123"
            POSTGRES_MAX_POOL_SIZE: "10"
            POSTGRES_CONNECTION_LIFETIME: "20000"
        healthcheck:
          test: "curl --silent --fail localhost:9198/health || exit 1"
          interval: 50s
          timeout: 30s
          retries: 5
        depends_on: [discovery]
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints: [node.labels.type == regular] 
        networks: [kite, db, kafka, elastic]
    documents:
        image: eu.gcr.io/kite-221910/kafka-experiments-documents:latest
        ports: ["9094:9094", "9199:9199"]
        environment:
            DOCUMENTS_SERVICE_PORT: "9094"
            DOCUMENTS_SERVICE_MANAGEMENT_PORT: "9199"
            KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
            KAFKA_ZK_NODES: "zookeeper:2181"
            KAFKA_SCHEMA_REGISTRY: "http://schema_registry:9090"
            EUREKA_DEFAULT_ZONE_URL: "http://discovery:8761/eureka"
            ZIPKIN_URL: http://zipkin:9252
            MONGO_SERVER: "mongo:9598"
            MONGO_USER: "root"
            MONGO_PASSWORD: "root"
            MONGO_DB: "documents-new"
            MONGO_AUTH_DB: "admin"
        healthcheck:
          test: "curl --silent --fail localhost:9199/health || exit 1"
          interval: 50s
          timeout: 30s
          retries: 5
        depends_on: [discovery]
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                - node.labels.type == regular
        networks: [kite, mongo, kafka, elastic]
    regulations:
        image: eu.gcr.io/kite-221910/kafka-experiments-regulations:latest
        ports: ["9095:9095", "9196:9196"]
        environment:
            REGULATIONS_SERVICE_PORT: "9095"
            REGULATIONS_SERVICE_MANAGEMENT_PORT: "9196"
            KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
            KAFKA_ZK_NODES: "zookeeper:2181"
            KAFKA_SCHEMA_REGISTRY: "http://schema_registry:9090"
            EUREKA_DEFAULT_ZONE_URL: "http://discovery:8761/eureka"
            ZIPKIN_URL: http://zipkin:9252
            MONGO_SERVER: "mongo:9598"
            MONGO_USER: "root"
            MONGO_PASSWORD: "root"
            MONGO_DB: "documents-new"
            MONGO_AUTH_DB: "admin"
        healthcheck:
          test: "curl --silent --fail localhost:9196/health || exit 1"
          interval: 50s
          timeout: 30s
          retries: 5
        depends_on: [discovery]
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: 
                - node.labels.type == regular
        networks: [kite, mongo, kafka, elastic]
    discovery:
        image: eu.gcr.io/kite-221910/kafka-experiments-discovery:latest
        ports: ["8761:8761"]
        environment:
            BOOT_ADMIN_CLIENT_URL: "http://admin:8080"
            DISCOVERY_SERVICE_PORT: "8761"
            KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
        healthcheck:
          test: "curl --silent --fail localhost:8761/actuator/health || exit 1"
          interval: 50s
          timeout: 30s
          retries: 5
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.labels.type == regular] 
        networks: [kite, kafka]
    gateway:
        image: eu.gcr.io/kite-221910/kafka-experiments-gateway:latest
        ports: ["8762:8762"]
        environment:
            GATEWAY_SERVICE_PORT: "8762"
            EUREKA_DEFAULT_ZONE_URL: "http://discovery:8761/eureka"
            KAFKA_BOOTSTRAP_SERVERS: "broker:9092"
        # healthcheck:
          # test: ["CMD-SHELL", "curl", "--silent --fail localhost:8762/health || exit 1"]
          # interval: 30s
          # timeout: 30s
          # retries: 5
        depends_on: [discovery]
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.labels.type == regular] 
        networks: [kite, kafka]
    admin:
        image: eu.gcr.io/kite-221910/kafka-experiments-admin:latest
        ports: ["8080:8080"]
        environment:
            EUREKA_DEFAULT_ZONE_URL: "http://discovery:8761/eureka"
        # healthcheck:
          # test: ["CMD-SHELL", "curl", "--silent --fail localhost:8080/health || exit 1"]
          # interval: 30s
          # timeout: 30s
          # retries: 5
        depends_on: [discovery]
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.labels.type == regular] 
        networks: [kite]
networks:
    db:
        external: true
    mongo:
        external: true
    elastic:
        external: true
    kafka:
        external: true
    kite:
        driver: overlay